spring.application.name=roadmap-service

server.port=8081
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
spring.datasource.url=${DB_URI}
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
